In [1]:
import numpy as np
import matplotlib.pyplot as plt
import random
import csv
from astropy.table import Table, Column
from astropy import units as u
import scipy.stats as ss

The problem of my simulated dataset was, that there are a big overlap between different Diets, so after trying many models, I decided to make some experience on small but with different overlap shopping lists.

In [8]:
def shoppingProducts3(ageGroup, diet): #Major difference between diet categories, with some overlapping
    shoppingList = []
    
    if(diet == "Normal"):

        shoppingList =["Meat", "Chicken", "Fish", "Vegetables"]

    elif(diet == "Vegan"):

        shoppingList =["Fruits", "Pasta", "Vegetables"]

    elif(diet == "Vegeterian"):

        shoppingList =["Eggs", "Cheese", "Dairy", "Pasta"]
    
    cartSize = np.random.randint(1,len(shoppingList))   
    return np.random.choice(shoppingList, size = cartSize, replace=False)

In [21]:
def shoppingProducts2(ageGroup, sex, diet): #Absolute difference between diet categories, without overlapping
    shoppingList = []
    
    if(diet == "Normal"):

        shoppingList =["Meat", "Chicken", "Fish"]

    elif(diet == "Vegan"):

        shoppingList =["Fruits", "Pasta", "Vegetables"]

    elif(diet == "Vegeterian"):

        shoppingList =["Eggs", "Cheese", "Dairy"]
    
    cartSize = np.random.randint(1,len(shoppingList))   
    return np.random.choice(shoppingList, size = cartSize, replace=False)

In [545]:
def shoppingProducts(ageGroup, diet): #Small difference between diet categories, with major overlapping
    shoppingList = []
    
    if(ageGroup == 1):

        if(diet == "Normal"):

            shoppingList =["Fruits", "Sweets", "Dairy", "Snacks", "Meat", "Pasta", "Bread", "Freezed Meal", "Cat Food"]

        elif(diet == "Vegan"):

            shoppingList =["Fruits", "Sweets", "Snacks", "others", "Pasta", "Bread", "Freezed Meal", "Cat Food"]

        elif(diet == "Vegeterian"):

            shoppingList =["Fruits", "Sweets", "Dairy", "Snacks", "Pasta", "Bread", "Freezed Meal","Cat Food"]

    elif(ageGroup == 2):

        if(diet == "Normal"):

            shoppingList =["Fruits","Vegtables", "Sweets", "Dairy", "Snacks", "Meat", "Houshold", "Baby Food", "Cat Food","Bio Products", "others", "Bread", "Pasta"]

        elif(diet == "Vegan"):

            shoppingList =["Fruits","Vegtables", "Sweets", "Snacks", "Houshold", "Baby Food", "others"]

        elif(diet == "Vegeterian"):

            shoppingList =["Fruits","Vegtables", "Sweets", "Snacks", "Houshold", "Baby Food", "others", "Dairy"]

    elif(ageGroup == 3):
        
        if(diet == "Normal"):

            shoppingList =["Fruits","Vegtables", "Sweets", "Dairy", "Snacks", "Meat", "Houshold","Bio Products", "Baby Food", "others", "Bread", "Pasta"]

        elif(diet == "Vegan"):

            shoppingList =["Fruits","Vegtables", "Sweets", "Snacks", "Houshold", "Baby Food", "others", "Bread", "Pasta"]

        elif(diet == "Vegeterian"):

            shoppingList =["Fruits","Vegtables", "Sweets", "Snacks", "Houshold", "Baby Food", "others", "Dairy", "Bread", "Pasta"]

    elif(ageGroup == 4):

        if(diet == "Normal"):

            shoppingList =["Fruits","Vegtables", "Dairy", "Meat", "Houshold", "others", "Bread", "Pasta", "Bio Products","Bio Products"]

        elif(diet == "Vegan"):

            shoppingList =["Fruits","Vegtables", "Houshold", "others","Bread", "Pasta","Bio Products"]

        elif(diet == "Vegeterian"):

            shoppingList =["Fruits","Vegtables", "Houshold", "others", "Dairy","Bread", "Pasta","Bio Products"]

    elif(ageGroup == 5):
        if(diet == "Normal"):

            shoppingList =["Fruits","Vegtables", "Dairy", "Meat", "Houshold", "others","Bread", "Dairy", "Bio Products"]

        elif(diet == "Vegan"):

            shoppingList =["Fruits","Vegtables", "Houshold", "others", "Bread", "others","Bread", "Bio Products"]

        elif(diet == "Vegeterian"):

            shoppingList =["Fruits","Vegtables", "Houshold",  "others", "Bread","Bread", "Bio Products"]
    
    cartSize = np.random.randint(1,len(shoppingList))   
    return np.random.choice(shoppingList, size = cartSize, replace=False)

In [22]:
consumerCount = 500
ageGroups =  [1, 2, 3, 4, 5]
dietGroups = ["Normal", "Vegan", "Vegeterian"]

In [23]:
with open('ConsumerData.csv','w',newline='') as fp:
    writer = csv.writer(fp, delimiter=',')
    writer.writerow(["ConsumerID", "Age", "Product", "Diet"])    
        
    for i in range(consumerCount):
        consumerId = i+1
        age = np.random.choice(ageGroups, size = 1)[0]
        diet = np.random.choice(dietGroups, size = 1)[0]
        
        #Choose different product generation methods
        cart = shoppingProducts3(age, diet)
        
        for j in range(len(cart)):
            print(consumerId, age,cart[j],diet) 
            writer.writerow((consumerId, age,cart[j], diet))

1 5 Eggs Vegeterian
2 5 Vegetables Vegan
3 2 Chicken Normal
3 2 Fish Normal
3 2 Meat Normal
4 3 Dairy Vegeterian
4 3 Pasta Vegeterian
4 3 Cheese Vegeterian
5 4 Pasta Vegan
6 3 Vegetables Normal
7 1 Cheese Vegeterian
7 1 Dairy Vegeterian
7 1 Pasta Vegeterian
8 3 Vegetables Vegan
9 5 Fruits Vegan
9 5 Vegetables Vegan
10 4 Fruits Vegan
11 4 Fruits Vegan
11 4 Pasta Vegan
12 1 Fruits Vegan
13 5 Pasta Vegan
14 5 Cheese Vegeterian
15 2 Vegetables Normal
16 3 Chicken Normal
17 5 Chicken Normal
17 5 Meat Normal
17 5 Fish Normal
18 5 Vegetables Vegan
19 1 Dairy Vegeterian
19 1 Eggs Vegeterian
20 4 Pasta Vegan
20 4 Vegetables Vegan
21 3 Fish Normal
21 3 Vegetables Normal
21 3 Chicken Normal
22 1 Meat Normal
22 1 Vegetables Normal
22 1 Fish Normal
23 2 Eggs Vegeterian
23 2 Pasta Vegeterian
23 2 Cheese Vegeterian
24 1 Chicken Normal
24 1 Fish Normal
24 1 Vegetables Normal
25 5 Dairy Vegeterian
26 4 Pasta Vegeterian
26 4 Cheese Vegeterian
27 3 Meat Normal
28 2 Chicken Normal
29 1 Fish Normal
29 1 Me

272 5 Pasta Vegan
272 5 Fruits Vegan
273 5 Vegetables Vegan
274 2 Dairy Vegeterian
274 2 Eggs Vegeterian
274 2 Pasta Vegeterian
275 1 Pasta Vegan
276 5 Dairy Vegeterian
276 5 Cheese Vegeterian
276 5 Pasta Vegeterian
277 3 Eggs Vegeterian
278 5 Dairy Vegeterian
279 1 Cheese Vegeterian
280 2 Cheese Vegeterian
281 3 Eggs Vegeterian
281 3 Pasta Vegeterian
281 3 Dairy Vegeterian
282 3 Pasta Vegan
283 2 Pasta Vegan
284 3 Pasta Vegan
284 3 Vegetables Vegan
285 4 Chicken Normal
285 4 Meat Normal
286 5 Vegetables Normal
287 4 Vegetables Vegan
288 5 Vegetables Vegan
289 3 Vegetables Normal
289 3 Meat Normal
289 3 Chicken Normal
290 2 Fruits Vegan
291 5 Chicken Normal
291 5 Fish Normal
292 2 Vegetables Vegan
293 2 Chicken Normal
294 3 Pasta Vegan
295 2 Fruits Vegan
296 3 Vegetables Normal
296 3 Fish Normal
296 3 Chicken Normal
297 4 Pasta Vegan
298 2 Chicken Normal
299 5 Vegetables Vegan
300 4 Cheese Vegeterian
300 4 Eggs Vegeterian
301 3 Vegetables Vegan
302 2 Cheese Vegeterian
302 2 Pasta Veget

In [24]:
import keras
from keras.models import Sequential 
from keras.layers import Dense, Dropout, Activation
from keras.optimizers import SGD
import pandas as pd
import tensorflow as tf

Import and spilt the data set. X is going contain Age group and products, y is the diet, which should be predicted later, in respect to the X.

In [25]:
dataset = pd.read_csv('ConsumerData.csv')
X = dataset.iloc[:, 1:-1].values
y = dataset.iloc[:, -1:].values 

In [26]:
print(X)

[[5 'Eggs']
 [5 'Vegetables']
 [2 'Chicken']
 ...
 [3 'Chicken']
 [4 'Dairy']
 [4 'Eggs']]


In [27]:
print(y)

[['Vegeterian']
 ['Vegan']
 ['Normal']
 ['Normal']
 ['Normal']
 ['Vegeterian']
 ['Vegeterian']
 ['Vegeterian']
 ['Vegan']
 ['Normal']
 ['Vegeterian']
 ['Vegeterian']
 ['Vegeterian']
 ['Vegan']
 ['Vegan']
 ['Vegan']
 ['Vegan']
 ['Vegan']
 ['Vegan']
 ['Vegan']
 ['Vegan']
 ['Vegeterian']
 ['Normal']
 ['Normal']
 ['Normal']
 ['Normal']
 ['Normal']
 ['Vegan']
 ['Vegeterian']
 ['Vegeterian']
 ['Vegan']
 ['Vegan']
 ['Normal']
 ['Normal']
 ['Normal']
 ['Normal']
 ['Normal']
 ['Normal']
 ['Vegeterian']
 ['Vegeterian']
 ['Vegeterian']
 ['Normal']
 ['Normal']
 ['Normal']
 ['Vegeterian']
 ['Vegeterian']
 ['Vegeterian']
 ['Normal']
 ['Normal']
 ['Normal']
 ['Normal']
 ['Normal']
 ['Vegan']
 ['Vegan']
 ['Vegeterian']
 ['Vegeterian']
 ['Vegeterian']
 ['Normal']
 ['Vegan']
 ['Vegeterian']
 ['Vegeterian']
 ['Vegeterian']
 ['Vegeterian']
 ['Vegeterian']
 ['Vegan']
 ['Vegan']
 ['Vegan']
 ['Vegan']
 ['Vegeterian']
 ['Vegeterian']
 ['Vegeterian']
 ['Vegeterian']
 ['Normal']
 ['Vegeterian']
 ['Vegeterian']


Transfoming non numerical values to numeric values

In [28]:
#print (np.unique(y, return_inverse=True)[1])
#print(l)
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X[:, 1] = le.fit_transform(X[:, 1])
#X[:, 2] = le.fit_transform(X[:, 2])
y[:, 0] = le.fit_transform(y[:, 0])
y=y.astype('int')

x_train is the training data set.
y_train is the set of labels to all the data in x_train.

x_test is the test data set.
y_test is the set of labels to all the data in x_test.


In [29]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

 finds a line that best fits a collection of observations.

In [30]:
from sklearn.preprocessing import MinMaxScaler
sc = MinMaxScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [31]:
# mlp for multi-label classification
from numpy import mean
from numpy import std
from sklearn.datasets import make_multilabel_classification
from sklearn.model_selection import RepeatedKFold
from keras.models import Sequential
from keras.layers import Dense
from sklearn.metrics import accuracy_score
from sklearn.neural_network import MLPRegressor
from sklearn.model_selection import train_test_split
from sklearn.datasets import fetch_california_housing
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import r2_score
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
from sklearn.neighbors import KNeighborsClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.naive_bayes import GaussianNB

# get the model
def get_model(dimX, dimY):
    model = Sequential()
    model.add(Dense(20, input_dim=dimX, kernel_initializer='he_uniform', activation='relu'))
    model.add(Dense(dimY, activation='sigmoid'))
    model.compile(loss='binary_crossentropy', optimizer='adam')
    return model
#multilayer Regression. The activation function is relu, which means 0 for x=<0 and x for x>0
def CreateModelAndFitMLPReg():
    model = MLPRegressor(hidden_layer_sizes=(64,64,64),activation="relu" ,random_state=1, max_iter=2000)
    model.fit(X_train, y_train)
    return model

#Finding the K nearest neigbour of test data. We think of training dara as vectors in space, finding the nearest neighbours
#calculating its distance to each of them 
def CreateModelAndFitKNN(X_train, y_train):
    model = KNeighborsClassifier()
    # fit model
    model.fit(X_train, y_train)
    print('Accuracy of K-NN classifier on training set: {:.2f}'
         .format(model.score(X_train, y_train)))
    print('Accuracy of K-NN classifier on test set: {:.2f}'
         .format(model.score(X_test, y_test)))
    return model



#Decision Tree
def CreateModelAndFitDecTree(X_train, y_train):
    clf = DecisionTreeClassifier().fit(X_train, y_train)
    print('Accuracy of Decision Tree classifier on training set: {:.2f}'
         .format(clf.score(X_train, y_train)))
    print('Accuracy of Decision Tree classifier on test set: {:.2f}'
         .format(clf.score(X_test, y_test)))
    return clf


#define model
#model = get_model2()

model = CreateModelAndFitKNN(X_train, y_train)

# make a prediction on the test set
y_pred = model.predict(X_test)

print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

Accuracy of K-NN classifier on training set: 0.84
Accuracy of K-NN classifier on test set: 0.81
[[46 15  0]
 [ 2 49  4]
 [ 0 13 50]]
              precision    recall  f1-score   support

           0       0.96      0.75      0.84        61
           1       0.64      0.89      0.74        55
           2       0.93      0.79      0.85        63

    accuracy                           0.81       179
   macro avg       0.84      0.81      0.81       179
weighted avg       0.85      0.81      0.82       179



C:\Users\MANI\Anaconda2\lib\site-packages\ipykernel_launcher.py:39: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
